name: Build Vite Site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Kalau butuh ENV untuk client, set di "Variables" (Actions → Secrets and variables → Variables)
      # dan semua var harus diawali VITE_*
      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Zip dist
        run: |
          cd dist
          zip -r ../site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.zip
